# This yaml file assumes the RabbitMq cluster operator has
# already been installed to the kubernetes cluster.
# Installing it is outside the scope of this example.
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: interaction-broker
  namespace: discord-microservice
spec:
  persistence:
    storage: 0 # No persistence
  resources:
    requests:
      cpu: 250m
      memory: 500M
    limits:
      cpu: 500m
      memory: 1Gi